# Which worlds should this be enabled in?
# Unlisted worlds will allow normal spawning.
enabled_worlds:
    - example_world
    - example_world_nether

# Default settings for any world and any biome.
# All settings will fall back to this if not specifically set in perWorld/perBiome settings
default:
    CHICKEN:
        spawnChance: 50
    COW:
        spawnChance: 50
    HORSE:
        spawnChance: 50
    OCELOT:
        spawnChance: 50
    PIG:
        spawnChance: 50
    SHEEP:
        spawnChance: 50
    WOLF:
        spawnChance: 50
        
# Customized world settings, just add world name for the specific world. 
# Any enabled_worlds that are NOT in this section will use the default settings. 
# Any worlds added here that are NOT in enabled worlds will still be disabled.

example_world:
    CHICKEN:
        spawnChance: 50  #default for this mob for this world.
        PLAINS:
            spawnChance: 100
    COW:
        spawnChance: 50  #default for this mob for this world.
        PLAINS:
            spawnChance: 100            
    HORSE:
        spawnChance: 50  #default for this mob for this world.
        PLAINS:
            spawnChance: 100
    OCELOT:
        spawnChance: 50  #default for this mob for this world.
        PLAINS:
            spawnChance: 50
    PIG:
        spawnChance: 50  #default for this mob for this world.
        PLAINS:
            spawnChance: 100
    SHEEP:
        spawnChance: 50  #default for this mob for this world.
        PLAINS:
            spawnChance: 100
    WOLF:
        spawnChance: 50  #default for this mob for this world.
        PLAINS:
            spawnChance: 100    
                     
# Enable logging (for debugging, generally leave this false unless you are having problems)
# Note that on production servers with lots of chicken farms this log could get very big!
debug_log: false
