# Which worlds should this be enabled in?
# Unlisted worlds will allow normal spawning.
enabled_worlds:
    example_world
    example_world_nether

# Default settings for any world and any biome.
# All settings will fall back to this if not specifically set in perWorld/perBiome settings
default:
    BEE:
        spawnChance: 50
    CAT:
        spawnChance: 50        
    CHICKEN:
        spawnChance: 50
    COW:
        spawnChance: 50
    DONKEY:
        spawnChance: 50 
    FOX:
        spawnChance: 50 
    HOGLIN:
        spawnChance: 50 
    HORSE:
        spawnChance: 50
    LLAMA:
        spawnChance: 50 
    MUSHROOM_COW:
        spawnChance: 50
    OCELOT:
        spawnChance: 50
    PANDA:
        spawnChance: 50 
    PIG:
        spawnChance: 50
    RABBIT:
        spawnChance: 50
    SHEEP:
        spawnChance: 50
    STRIDER:
        spawnChance: 50 
    TURTLE:
        spawnChance: 50         
    WOLF:
        spawnChance: 50

# Customized world settings, just add world name for the specific world. 
# Any enabled_worlds that are NOT in this section will use the default settings. 
# Any worlds added here that are NOT in enabled worlds will still be disabled.

example_world:
    BEE:
        spawnChance: 50  #default for this mob for this world.
        PLAINS:
            spawnChance: 100
        SUNFLOWER_PLAINS:
            spawnChance: 100
    CAT:
        spawnChance: 50  #default for this mob for this world.         
    CHICKEN:
        spawnChance: 50  #default for this mob for this world.
        PLAINS:
            spawnChance: 100
        SUNFLOWER_PLAINS:
            spawnChance: 100
    COW:
        spawnChance: 50  #default for this mob for this world.
        PLAINS:
            spawnChance: 100 
        SUNFLOWER_PLAINS:
            spawnChance: 100
    DONKEY:
        spawnChance: 50  #default for this mob for this world.
        PLAINS:
            spawnChance: 100 
        SUNFLOWER_PLAINS:
            spawnChance: 100
    FOX:
        spawnChance: 50  #default for this mob for this world.
    HOGLIN:
        spawnChance: 0  #default for this mob for this world.
    HORSE:
        spawnChance: 50  #default for this mob for this world.
        PLAINS:
            spawnChance: 100
        SUNFLOWER_PLAINS:
            spawnChance: 100
    LLAMA:
        spawnChance: 50  #default for this mob for this world.
    MUSHROOM_COW:
        spawnChance: 0  #default for this mob for this world.   
        MUSHROOM_ISLAND:
            spawnChance: 50 
        MUSHROOM_SHORE:
            spawnChance: 50 
    OCELOT:
        spawnChance: 25  #default for this mob for this world.
        JUNGLE: 
            spawnChance: 100
        JUNGLE_EDGE:
            spawnChance: 100
        JUNGLE_EDGE_MOUNTAINS:
            spawnChance: 100
        JUNGLE_HILLS:
            spawnChance: 100
        JUNGLE_MOUNTAINS:
            spawnChance: 100
    PANDA:
        spawnChance: 50  #default for this mob for this world.
    PIG:
        spawnChance: 50  #default for this mob for this world.
        PLAINS:
            spawnChance: 100
        SUNFLOWER_PLAINS:
            spawnChance: 100
    RABBIT:
        spawnChance: 50  #default for this mob for this world.
        PLAINS:
            spawnChance: 100
    SHEEP:
        spawnChance: 50  #default for this mob for this world.
        PLAINS:
            spawnChance: 100
        SUNFLOWER_PLAINS:
            spawnChance: 100
    STRIDER:
        spawnChance: 0  #default for this mob for this world.
    TURTLE:
        spawnChance: 50  #default for this mob for this world.
    WOLF:
        spawnChance: 50  #default for this mob for this world.
        FOREST:
            spawnChance: 100
        FOREST_HILLS:
            spawnChance: 100
        ROOFED_FOREST:
            spawnChance: 100
        TAIGA:
            spawnChance: 100
        TAIGA_HILLS: 
            spawnChance: 100

example_world_nether:
    BEE:
        spawnChance: 0
    CAT:
        spawnChance: 0        
    CHICKEN:
        spawnChance: 0
    COW:
        spawnChance: 0
    DONKEY:
        spawnChance: 0 
    FOX:
        spawnChance: 0 
    HOGLIN:
        spawnChance: 50 
    HORSE:
        spawnChance: 0
    LLAMA:
        spawnChance: 0 
    MUSHROOM_COW:
        spawnChance: 0
    OCELOT:
        spawnChance: 0
    PANDA:
        spawnChance: 0 
    PIG:
        spawnChance: 0
    RABBIT:
        spawnChance: 0
    SHEEP:
        spawnChance: 0
    STRIDER:
        spawnChance: 50 
    TURTLE:
        spawnChance: 0         
    WOLF:
        spawnChance: 0

# Enable logging (for debugging, generally leave this false unless you are having problems)
# Note that on production servers with lots of farms this log could get very big!
debug_log: false
